//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleTransporte
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_TRANSPORTE
    {
        public int id { get; set; }
        public string rua { get; set; }
        public string bairro { get; set; }
        public string horario { get; set; }
    }
}
